lib/goalspot_web/router.ex
defmodule GoalspotWeb.Router do
  use GoalspotWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GoalspotWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources("/tasks", TaskController) do
      resources("/subtasks", SubTaskController)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", GoalspotWeb do
  #   pipe_through :api
  # end
end

lib/goalspot/goal/task.ex
defmodule Goalspot.Goal.Task do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tasks" do
    field :description, :string
    field :done, :boolean, default: false
    field :name, :string
    field :reminder_at, :date
    has_many :subtasks, Goalspot.Goal.SubTask

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:name, :description, :done, :reminder_at])
    |> validate_required([:name, :description, :done, :reminder_at])
  end
end

lib/goalspot_web/controllers/task_controller.ex
defmodule GoalspotWeb.TaskController do
  use GoalspotWeb, :controller

  alias Goalspot.Goal
  alias Goalspot.Goal.{Task, SubTask}

  def index(conn, _params) do
    tasks = Goal.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Goal.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    case Goal.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Goal.get_task!(id)
    subtask_changeset  = Goal.change_sub_task(%SubTask{})
    render(conn, "show.html", task: task, subtask_changeset: subtask_changeset)
  end

  def edit(conn, %{"id" => id}) do
    task = Goal.get_task!(id)
    changeset = Goal.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Goal.get_task!(id)

    case Goal.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Goal.get_task!(id)
    {:ok, _task} = Goal.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
end

lib/goalspot_web/views/task_view.ex
defmodule GoalspotWeb.TaskView do
  use GoalspotWeb, :view
end

lib/goalspot_web/templates/task/edit.html.eex
<h1>Edit Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/goalspot_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :done %>
  <%= checkbox f, :done %>
  <%= error_tag f, :done %>

  <%= label f, :reminder_at %>
  <%= date_select f, :reminder_at %>
  <%= error_tag f, :reminder_at %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/goalspot_web/templates/task/index.html.eex
<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Done</th>
      <th>Reminder at</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.description %></td>
      <td><%= task.done %></td>
      <td><%= task.reminder_at %></td>

      <td>
        <%= link "Show", to: Routes.task_path(@conn, :show, task) %>
        <%= link "Edit", to: Routes.task_path(@conn, :edit, task) %>
        <%= link "Delete", to: Routes.task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: Routes.task_path(@conn, :new) %></span>

lib/goalspot_web/templates/task/new.html.eex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/goalspot_web/templates/task/show.html.eex
<h1>Show Task</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @task.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

  <li>
    <strong>Done:</strong>
    <%= @task.done %>
  </li>

  <li>
    <strong>Reminder at:</strong>
    <%= @task.reminder_at %>
  </li>

</ul>

<h3>SubTasks</h3>
<ul>
<%= for subtask <- @task.subtasks  do %>
  <li class="subtask"><%= subtask.name %></li>
<% end %>
</ul>

<h3>Add a SubTask</h3>
<%= form_for @subtask_changeset, Routes.task_sub_task_path(@conn, :create, @task), fn f -> %>
  <%= label f, :name %>
  <%= textarea f, :name %>
  <%= error_tag f, :name %>
  <div>
    <%= submit "Save" %>
  </div>
<% end %>

<span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task) %></span>
<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>